from proj06 import find_singers_vocab

data_dict = {'Adele': {'All I Ask': {'use', 'honesty', 'scared', 'hand', 'tell', 'door', 'pretend', 'last', 'sure', 'lovers', 'leave', 'forgiveness', 'say', 'ask', 'night', 'vicious', 'ends', 'love', 'coming', 'left', 'knows', 'asking', 'lesson', 'memory', 'wanna', 'heart', 'eyes', 'let', 'take', 'matters', 'give', 'way', 'play', 'cruel', 'friend', 'run', 'since', 'get', 'cause', 'hold', 'one', 'said', 'next', 'wrong', 'like', 'remember', 'tomorrow', 'need', 'speak', 'know', 'word'}, "Can't Let Go": {'lied', 'write', 'lump', 'truth', 'even', 'baby', 'tell', 'gave', 'die', 'save', 'dark', 'heaven', 'thinking', 'round', 'platter', 'go', 'went', 'feel', 'everything', 'hid', 'seam', 'loved', 'let', 'sometimes', 'throat', 'hope', 'yet', 'thought', 'wanted', 'oooh', 'time', 'kill', 'find', 'note', 'told', 'coat', 'slow', 'said', 'much', 'faked', 'life', 'like', 'hard', 'arms', 'know'}}, 'Bob Dylan': {'4Th Time Around': {'threw', 'else', 'filled', 'dirt', 'forgotten', 'waste', 'wasted', 'last', 'must', 'leave', 'words', 'worked', 'breaking', 'handed', 'ask', 'back', 'pockets', 'gallantly', 'go', 'went', 'picture', 'crutch', 'jamaican', 'loved', 'stood', 'better', 'screamed', 'till', 'tapped', 'waited', 'give', 'got', 'straightened', 'sense', 'brought', 'cried', 'covered', 'thought', 'forced', 'took', 'get', 'rum', 'finding', 'something', 'spit', 'make', 'buttoned', 'tried', 'look', 'face', 'wheelchair', 'hands', 'drum', 'felt', 'shoe', 'fell', 'piece', 'everybody', 'leaned', 'asked'}, 'A Satisfied Mind': {'fame', 'ones', 'money', 'start', 'old', 'certain', 'dreamed', 'leave', 'say', 'game', 'things', 'someone', 'suddenly', 'man', 'world', 'lifes', 'comes', 'everything', 'dime', 'loved', 'richer', 'ten', 'little', 'way', 'run', 'lost', 'fortune', 'get', 'time', 'one', 'far', 'times', 'satisfied', 'find', 'wading', 'life', 'doubt', 'hard', 'friends', 'heard', 'happened', 'know', 'many'}}}
instructor_data = {'Adele': {'thinking', 'forgiveness', 'asking', 'since', 'take', 'play', 'platter', 'tell', 'wanted', 'coat', 'eyes', 'baby', 'way', 'get', 'ends', 'next', 'lump', 'told', 'faked', 'went', 'night', 'coming', 'one', 'lovers', 'heart', 'lesson', 'need', 'seam', 'leave', 'oooh', 'friend', 'lied', 'like', 'time', 'speak', 'give', 'said', 'cause', 'matters', 'last', 'dark', 'honesty', 'knows', 'loved', 'say', 'gave', 'life', 'throat', 'feel', 'word', 'door', 'pretend', 'find', 'cruel', 'love', 'tomorrow', 'wanna', 'write', 'hold', 'even', 'everything', 'hid', 'hard', 'wrong', 'use', 'know', 'remember', 'much', 'ask', 'arms', 'sometimes', 'thought', 'run', 'die', 'go', 'save', 'hope', 'hand', 'heaven', 'let', 'truth', 'yet', 'kill', 'scared', 'memory', 'round', 'slow', 'note', 'vicious', 'sure', 'left'}, 'Bob Dylan': {'times', 'face', 'better', 'start', 'crutch', 'back', 'way', 'gallantly', 'shoe', 'get', 'got', 'spit', 'filled', 'screamed', 'friends', 'dirt', 'suddenly', 'money', 'went', 'sense', 'waited', 'finding', 'make', 'one', 'things', 'tapped', 'leave', 'must', 'something', 'hands', 'look', 'far', 'fortune', 'world', 'picture', 'doubt', 'time', 'wasted', 'happened', 'else', 'give', 'ten', 'richer', 'stood', 'fell', 'lifes', 'last', 'wheelchair', 'heard', 'took', 'loved', 'rum', 'say', 'life', 'pockets', 'till', 'ones', 'little', 'find', 'buttoned', 'piece', 'worked', 'leaned', 'wading', 'drum', 'man', 'everything', 'hard', 'jamaican', 'covered', 'know', 'someone', 'cried', 'ask', 'forced', 'thought', 'threw', 'run', 'game', 'certain', 'go', 'forgotten', 'felt', 'dime', 'lost', 'comes', 'breaking', 'many', 'asked', 'dreamed', 'tried', 'everybody', 'waste', 'fame', 'words', 'brought', 'straightened', 'handed', 'satisfied', 'old'}}

student_data = find_singers_vocab(data_dict)

print("student data:   ", student_data)
print("instructor data:", instructor_data)

assert student_data == instructor_data